// Shared EPStudy content that is intentionally kept out of version pages.
window.EPSTUDY_QUOTES = [
    { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { text: "The secret to getting ahead is getting started.", author: "Mark Twain" },
    { text: "Focus on the step in front of you, not the whole staircase.", author: "Anonymous" },
    { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
    { text: "Your potential is endless. Go do what you were created to do.", author: "Anonymous" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "It’s not about having time. It’s about making time.", author: "Unknown" },
    { text: "Soar higher today than you did yesterday.", author: "EPS Spirit" },
    { text: "A little progress each block beats a perfect plan you never start.", author: "EPStudy" },
    { text: "Do the assignment that future you will be relieved is finished.", author: "EPStudy" },
    { text: "Small choices compound into finished work.", author: "EPStudy" },
    { text: "When everything feels important, start with what is due soonest.", author: "EPStudy" },
    { text: "Preparation is quieter than panic and usually faster.", author: "EPStudy" },
    { text: "Protect your focus like it is part of the assignment.", author: "EPStudy" },
    { text: "The best study plan is the one you can actually follow today.", author: "EPStudy" },
    { text: "Make the next right task obvious, then do it.", author: "EPStudy" },
    { text: "Strong weeks are built one honest session at a time.", author: "EPStudy" },
    { text: "Start before it feels urgent.", author: "EPStudy" },
    { text: "Protect your focus like it is part of the assignment.", author: "EPStudy" },
    { text: "The best study plan is the one you can actually follow today.", author: "EPStudy" },
    { text: "Make the next right task obvious, then do it.", author: "EPStudy" },
    { text: "Strong weeks are built one honest session at a time.", author: "EPStudy" },
    { text: "Start before it feels urgent.", author: "EPStudy" },
    { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
    { text: "Procrastination is the art of keeping up with yesterday.", author: "Don Marquis" },
    { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
    { text: "There is no substitute for hard work.", author: "Thomas Edison" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { text: "Genius is 1% inspiration and 99% perspiration.", author: "Thomas Edison" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
    { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
    { text: "Teachers can open the door, but you must enter it yourself.", author: "Chinese Proverb" },
    { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
    { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
    { text: "Do the best you can until you know better. Then when you know better, do better.", author: "Maya Angelou" },
    { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
    { text: "Ninety percent of success is just showing up.", author: "Woody Allen" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { text: "Recipe for success: Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.", author: "William A. Ward" },
    { text: "Failure is the opportunity to begin again more intelligently.", author: "Henry Ford" },
    { text: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr." },
    { text: "Learning is never done without errors and defeat.", author: "Vladimir Lenin" },
    { text: "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", author: "Wayne Dyer" },
    { text: "It's not that I'm so smart, it's just that I stay with problems longer.", author: "Albert Einstein" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The authority of those who teach is often an obstacle to those who want to learn.", author: "Cicero" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "Perseverance is the hard work you do after you get tired of doing the hard work you already did.", author: "Newt Gingrich" },
    { text: "If people knew how hard I had to work to gain my mastery, it would not seem so wonderful at all.", author: "Michelangelo" },
    { text: "Continuous effort—not strength or intelligence—is the key to unlocking our potential.", author: "Winston Churchill" },
    { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
    { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
    { text: "Opportunities are usually disguised as hard work, so most people don't recognize them.", author: "Ann Landers" },
    { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
    { text: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Oliver Wendell Holmes Jr." },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
    { text: "He who asks a question is a fool for five minutes; he who does not ask a question remains a fool forever.", author: "Chinese Proverb" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { text: "The pain of study is only temporary. The pain of not learning is lifelong.", author: "Unknown" },
    { text: "Defeat is not the worst of failures. Not to have tried is the true failure.", author: "George Edward Woodberry" },
    { text: "You don't drown by falling in the water; you drown by staying there.", author: "Ed Cole" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
    { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
    { text: "It is wiser to find out than to suppose.", author: "Mark Twain" },
    { text: "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", author: "Alexander Graham Bell" },
    { text: "There are no traffic jams along the extra mile.", author: "Roger Staubach" },
    { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { text: "It is not the mountain we conquer, but ourselves.", author: "Sir Edmund Hillary" },
    { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
    { text: "Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", author: "Stephen King" },
    { text: "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.'", author: "Mary Anne Radmacher" },
    { text: "Nothing will work unless you do.", author: "Maya Angelou" },
    { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { text: "You can modify your dreams or magnify your skills.", author: "Jim Rohn" },
    { text: "The struggle you are in today is developing the strength you need for tomorrow.", author: "Robert Tew" },
    { text: "Diligence is the mother of good luck.", author: "Benjamin Franklin" },
    { text: "Learning without thought is labor lost; thought without learning is perilous.", author: "Confucius" },
    { text: "You are more powerful than you know; but you must act.", author: "Unknown" },
    { text: "Preparation meeting opportunity creates the offspring we call luck.", author: "Tony Robbins" },
    { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "The differences between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi" },
    { text: "Knowledge is power.", author: "Francis Bacon" },
    { text: "Great things are done by a series of small things brought together.", author: "Vincent Van Gogh" },
    { text: "I am always doing that which I cannot do, in order that I may learn how to do it.", author: "Pablo Picasso" },
    { text: "No thief, however skillful, can rob one of knowledge, and that is why knowledge is the best and safest treasure to acquire.", author: "L. Frank Baum" },
    { text: "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.", author: "Jim Rohn" },
    { text: "The only thing that overcomes hard luck is hard work.", author: "Harry Golden" },
    { text: "Be so good they can't ignore you.", author: "Steve Martin" },
    { text: "The calendar is more powerful than the clock; know what matters and assign a date to it.", author: "Unknown" },
    { text: "Character is the ability to carry out a good resolution long after the excitement of the moment has passed.", author: "Cavett Robert" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" }

  ];
